version: '3.8'

services:
  socketserver:
    restart: always
    container_name: bumpy_server
    image: bumpy_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5228:5228"
    volumes:
      - ./server:/usr/local/app

  client:
    restart: always
    container_name: bumpy_client
    image: bumpy:client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4367:4367"
    volumes:
      - ./client:/usr/local/client

  nginx:
    restart: always
    container_name: bumpy_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "7978:80"
